#!/bin/bash

echo "=== Исправление 502 Bad Gateway ==="
echo ""
echo "Проблема: Gunicorn упал из-за исчерпания пула подключений к БД"
echo ""
echo "Что было:"
echo "  - Пул: max_size=30, waiting=50"
echo "  - При нагрузке: 42 запроса ожидали соединения"
echo "  - Результат: таймаут, systemd убил сервис"
echo ""
echo "Исправления:"
echo "  ✅ DB_POOL_MAX_SIZE: 30 → 100"
echo "  ✅ DB_POOL_MAX_WAITING: 50 → 200"
echo "  ✅ DB_POOL_TIMEOUT: 30s → 60s"
echo "  ✅ DB_POOL_MIN_SIZE: 2 → 5"
echo ""
echo "Для применения выполните:"
echo ""
echo "sudo systemctl restart trading_assistant"
echo ""
echo "Проверьте статус:"
echo "sudo systemctl status trading_assistant"
echo ""
echo "Если снова будет 502, проверьте логи:"
echo "sudo journalctl -u trading_assistant -f"