#!/bin/bash

echo "=== Quick Restart Script ==="
echo ""
echo "Перезапуск trading_assistant для применения новых настроек пула БД"
echo ""
echo "Новые параметры пула:"
echo "  DB_POOL_MAX_SIZE: 100 (было 30)"
echo "  DB_POOL_MAX_WAITING: 200 (было 50)"
echo "  DB_POOL_TIMEOUT: 60s (было 30s)"
echo "  DB_POOL_MIN_SIZE: 5 (было 2)"
echo ""
echo "Выполните команду с правами sudo:"
echo ""
echo "sudo systemctl restart trading_assistant"
echo ""
echo "Затем проверьте статус:"
echo "systemctl status trading_assistant"
echo ""
echo "И проверьте логи на применение новых параметров:"
echo "journalctl -u trading_assistant -n 50 | grep -E 'min=|max=|Пул'"
