#!/bin/bash

echo "=== Перезапуск всех сервисов Trading Assistant ==="
echo ""
echo "Новые настройки пула БД добавлены в .env:"
echo "  DB_POOL_MAX_SIZE=100"
echo "  DB_POOL_MAX_WAITING=200" 
echo "  DB_POOL_TIMEOUT=60"
echo "  DB_POOL_MIN_SIZE=5"
echo ""
echo "ВАЖНО: В systemd service файле неправильный DB_HOST=localhost"
echo "Должно быть DB_HOST=10.8.0.1"
echo ""
echo "Для применения изменений выполните:"
echo ""
echo "1. Исправьте /etc/systemd/system/trading_assistant.service:"
echo "   sudo sed -i 's/DB_HOST=localhost/DB_HOST=10.8.0.1/' /etc/systemd/system/trading_assistant.service"
echo ""
echo "2. Перезагрузите systemd конфигурацию:"
echo "   sudo systemctl daemon-reload"
echo ""
echo "3. Перезапустите сервис:"
echo "   sudo systemctl restart trading_assistant"
echo ""
echo "4. Проверьте логи:"
echo "   journalctl -u trading_assistant -n 100 | grep 'max='"
echo ""
echo "Должно показать: min=5, max=100"
